runtime: python37
entrypoint: uwsgi --http-socket :8080 --module MyAppRest.autoapp --callable app --master --processes 1 --threads 2
env_variables:
  GCP_PROJECT_ID: $GCP_PROJECT_ID
  DEPLOY_VERSION: $DEPLOY_VERSION

inbound_services:
  - warmup

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

automatic_scaling:
  min_instances: 1