name: MyAppRest unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: |
        docker-compose -f docker-compose.test.yml -p MyAppRest-tests up --exit-code-from tests --force-recreate --build
